name = "websites"
#main = "./index.js"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2025-05-20"
compatibility_flags = [ "nodejs_compat" ]

bucket = "out"
entry-point = "./"

#[assets]
#directory = "./dist"

[triggers]
crons = ["*/30 * * * *"]

[site]
# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#name = "websites"
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="c54dd5e27d6a474faebab038fa23d872"}]
#route="websites.dominioweb.com.mx/*"
