name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  repository_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: enable corepack
      run: corepack enable
    - name: Set Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - run: yarn build
      env:
        NODE_ENV: production
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
        preCommands: |
          wrangler kv:namespace create KV_STATUS_PAGE || true
          export KV_NAMESPACE_ID=$(npx @cloudflare/wrangler@1 kv:namespace list 2> >(tee stderr.log >&2) | head -1 | node -pe "JSON.parse(fs.readFileSync('/dev/stdin').toString()).find(kv => kv.title.includes('KV_STATUS_PAGE')).id")
          echo "[env.production]" >> wrangler.toml
          echo "kv_namespaces = [{binding=\"KV_STATUS_PAGE\", id=\"${KV_NAMESPACE_ID}\"}]" >> wrangler.toml
        postCommands: |
          yarn kv-gc
        environment: production
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
